/** Rutas internas en un solo lugar (evita strings sueltos y enlaces rotos). */
export const routes = {
  home: "/",
  shop: "/shop",
  product: (slug: string) => `/shop/${encodeURIComponent(slug)}`,
  cart: "/cart",
  checkout: "/checkout",
  account: "/account",
  accountOrders: "/account/orders",
  accountLogin: "/account/login",
  accountRegister: "/account/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  resetSuccess: "/reset-success",
  verifyEmail: "/verify-email",
  verificationSuccess: "/verification-success",
  terms: "/terminos",
  privacy: "/privacidad",
  admin: "/admin",
  adminLogin: "/admin/login",
  adminProducts: "/admin/products",
  adminProductNew: "/admin/products/new",
  adminProduct: (id: string) => `/admin/products/${encodeURIComponent(id)}`,
  adminProductDelete: (id: string) => `/admin/products/${encodeURIComponent(id)}/eliminar`,
  adminOrders: "/admin/orders",
  adminInventory: "/admin/inventory",
  adminTaxes: "/admin/taxes",
  adminShipping: "/admin/shipping",
  adminCustomers: "/admin/customers",
  adminUsers: "/admin/users",
  adminUser: (id: string) => `/admin/users/${encodeURIComponent(id)}`,
  staffInvitation: "/staff-invitation",
} as const;

/** Páginas reales del sitio principal (azulclaritocr.com), para enlaces cruzados. */
export const mainSiteRoutes = {
  music: "/musica.html",
  ep: "/ep.html",
  books: "/libros.html",
} as const;
